### ISSUE TITLE
Hide empty card badges.

### ISSUE THREAD

**Issue by MarkPearce** [zeel01/monarch#45]
When the card data is null, do not show the related badge divs
![issue_emptycontainers](https://user-images.githubusercontent.com/6976378/155422250-20f874d9-dc72-48e3-acff-c5a195e5796e.png)

**Comment by zeel01** [comment]
You can disable unused badges in the module settings. All except `name` which for accessibility reasons should never be null.

Badges do not automatically get hidden if null on purpose.  For the default badges, this is because I want to default behavior to cling closer to Core, wherein there would still be a conspicuous blank space for the missing values. For badges added via the API, hiding these should be handled through the API by the module/system that adds them.
